<?php
/**
 * @file uc_field_attribute.module
 * Ubercart attributes an options based on Backdrop core fields
 */

/**
 * Implements hook_menu().
 */
function uc_field_attribute_menu() {
  // Menu items for default product class attributes and options.
  $items['admin/store/products/classes/%uc_product_class/field-attribute'] = array(
    'title' => 'Field Attributes',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('uc_field_attribute_form', 4, 'class'),
    'access callback' => 'uc_attribute_product_class_access',
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
    'file' => 'uc_field_attribute.admin.inc',
  );
  return $items;
}
/**
 * Implements hook_config_info().
 */
function uc_field_attribute_config_info() {
  $prefixes['uc_field_attribute.settings'] = array(
    'label' => t('UC Field attributes settings'),
    'group' => t('Configuration'),
  );
  return $prefixes;
}

/**
 * Load settings
 *
 * @param string $bundle_name
 *
 * @return object
 */
function uc_field_attribute_load_settings($bundle_name) {
  $settings = config_get('uc_field_attribute.settings', "uc_field_attribute_$bundle_name");
  return (object) $settings;
}

/**
 * Save settings
 *
 * @param string $bundle_name
 * @param array $settings
 */
function uc_field_attribute_save_settings($bundle_name, $settings) {
  config_set('uc_field_attribute.settings', "uc_field_attribute_$bundle_name", (array) $settings);
}

/**
 * Implements hook_node_insert().
 */
function uc_field_attribute_node_insert($node) {
  if (!array_key_exists($node->type, uc_product_class_load())) {
    return;
  }
  module_load_include('inc', 'uc_field_attribute', 'uc_field_attribute');
  return _uc_field_attribute_nodeapi($node, "insert");
}

/**
 * Implements hook_node_update().
 */
function uc_field_attribute_node_update($node) {
  if (!array_key_exists($node->type, uc_product_class_load())) {
    return;
  }
  module_load_include('inc', 'uc_field_attribute', 'uc_field_attribute');
  return _uc_field_attribute_nodeapi($node, "update");
}

/**
 * Implements hook_node_delete().
 */
function uc_field_attribute_node_delete($node) {
  if (!array_key_exists($node->type, uc_product_class_load())) {
    return;
  }
  module_load_include('inc', 'uc_field_attribute', 'uc_field_attribute');
  return _uc_field_attribute_node_delete($node);
}
